#!/usr/bin/env bash

if [ "$1" == "run" ];
then
	export $(cat .env | grep -v '^#' | xargs)
	go run -ldflags "-X main.version=$(git rev-parse --short HEAD)" .
elif  [ "$1" == "build" ];
then
	go build -o vigo360-fuentes -ldflags "-X main.version=$(git rev-parse --short HEAD)" .
fi
