#!/usr/bin/env bash

if [ "$1" == "run" ];
then
	sass --source-map --embed-source-map -s compressed static/style.scss:static/style.css
	export $(cat .env | grep -v '^#' | xargs)
	go run -ldflags "-X main.version=$(git rev-parse --short HEAD)" .
elif  [ "$1" == "build" ];
then
	sass --source-map --embed-source-map -s compressed static/style.scss:static/style.css
	go build -o fuentes -ldflags "-X main.version=$(git rev-parse --short HEAD)" .
fi
